### ISSUE TITLE
Build failure on GCC 4.8 and 4.9

### ISSUE THREAD

**Issue by grisumbras** [boostorg/charconv#174]
https://drone.cpp.al/boostorg/json/1482/14/2

I've also noticed that GCC 4.8 is not tested in CI. Is it not supported?

**Comment by grisumbras** [comment]
> * GCC 5 or later
> * Clang 3.8 or later
> * Visual Studio 2015 (14.0) or later

Indeed it is not. The interesting thing here is that all of these compilers support C++14, so there's no need for Charconv to support C++11.

**Comment by mborland** [comment]
It is not. Recently there was an attempt to make them work that I was not interested in supporting: https://github.com/boostorg/charconv/pull/165 and https://github.com/boostorg/charconv/pull/170. 

> The interesting thing here is that all of these compilers support C++14, so there's no need for Charconv to support C++11.

The support for C++14 is incomplete in all of those. To get everything working as it should in a different library the bar had to be raised a fair amount: https://cppalliance.org/decimal/overview.html

**Comment by grisumbras** [comment]
I see. Unfortunately this blocks JSON from using Charconv for the time being.

**Comment by mborland** [comment]
> I see. Unfortunately this blocks JSON from using Charconv for the time being.

Do you actually have demand for 4.X? Your benchmarks have huge gains by making the change. Add a note into 1.85 that says you plan to drop support in 1.86.

**Comment by grisumbras** [comment]
> Do you actually have demand for 4.X? Your benchmarks have huge gains by making the change. Add a note into 1.85 that says you plan to drop support in 1.86.

GCC 4.8 and 4.9 are used as default compilers on some older versions of Linux. I don't have a way to actually check how many people rely on support for these compilers.

**Comment by pdimov** [comment]
Maybe you can ask on the mailing list and/or Reddit? The ML has a lot of reach because there are many subscribers who don't post.

**Comment by grisumbras** [comment]
Great idea.

**Comment by mborland** [comment]
> > Do you actually have demand for 4.X? Your benchmarks have huge gains by making the change. Add a note into 1.85 that says you plan to drop support in 1.86.
> 
> GCC 4.8 and 4.9 are used as default compilers on some older versions of Linux. I don't have a way to actually check how many people rely on support for these compilers.

RHEL 7 goes to extended maintenance in May which seems to be the only major distro with <=4.8 as the default that is not EOL. Concur with asking the ML.

**Comment by pdimov** [comment]
RH killed CentOS so the only live one remains on 4.8, or did last I checked. There were some alternatives in development, but I don't follow them so I don't know what's the current state of things in CentOSland.

**Comment by pdimov** [comment]
> CentOS-7 updates until June 30, 2024

Goes EOL soon. :-)

**Comment by mborland** [comment]
> RH killed CentOS so the only live one remains on 4.8, or did last I checked. There were some alternatives in development, but I don't follow them so I don't know what's the current state of things in CentOSland.

Alma and Rocky are the two big ones I know of, and they are both RHEL 8 derivatives which has GCC 8 as default. 

> CentOS-7 updates until June 30, 2024

Perfect
