### ISSUE TITLE
Tags linked to the Boost release version

### ISSUE THREAD

**Issue by yurybura** [boostorg/charconv#175]
All libraries have git tags linked to the Boost release version, except charconv. Could you add tag boost-1.85.0.beta1?

**Comment by pdimov** [comment]
These tags are created by the release manager (@mclow ). It's not clear why Charconv doesn't have them.

**Comment by pdimov** [comment]
Boost.Scope doesn't seem to have a tag either.

**Comment by pdimov** [comment]
The `--init` option is probably missing from `git submodule update` somewhere in the release scripts/procedures. :-)

**Comment by mclow** [comment]
Fixed.

**Comment by mborland** [comment]
The boost-1.85.0 tag is on current develop and the boost-1.85.0.beta1 tag is against a random pre-review merge commit. What actually went out in release since the tags are seemingly incorrect (i.e. not aligned to master)?

**Comment by mclow** [comment]
Dang - can't get anything right today :-(

The 1.85.0 tag has been fixed.
The beta tag should be attached to the last commit on master before the beta release - is that not the case?

**Comment by mclow** [comment]
The beta tag is indeed screwed up - I picked the wrong date. Will fix immediately.

**Comment by mborland** [comment]
> Dang - can't get anything right today :-(
> 
> The 1.85.0 tag has been fixed. The beta tag should be attached to the last commit on master before the beta release - is that not the case?

No it is well behind master (Tagged on commit from 12/11/2023). Scope seems to be in the same position.

**Comment by mclow** [comment]
Yeah. I did the same thing for scope - looked for the state as of the 1.84.0 release :-(
It appears that the 1.85.0 and the 1.85.0.beta1 tag should refer to the same commit - and they do so now.

**Comment by mborland** [comment]
Looks good now. Thanks for the quick fix.

**Comment by mclow** [comment]
You're welcome. Sorry for the confusion.
