### ISSUE TITLE
Fail to compile on ppc64le

### ISSUE THREAD

**Issue by sdebionne** [boostorg/charconv#194]
It looks like some floating point extension are not properly detected on ppc64le (gxx 13.2):

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=915982&view=logs&j=8c139a40-380b-5518-bf6b-edcb18cbf319&t=e71f8d0d-13be-528e-b5e7-bfc20e0db699&l=18942

cc: https://github.com/conda-forge/boost-feedstock/pull/196

**Comment by mborland** [comment]
Can you try running from develop? I fixed a few ppc64le related issues since release, and locally everything seems fine with both long double ABIs.

**Comment by sdebionne** [comment]
Hi Matt, sure I can add patches to the build. Were you referring to https://github.com/boostorg/charconv/commit/100473b1dc3c3dfff0513e584c8f447824c7e34c ?

**Comment by mborland** [comment]
Yes. #193 will apply as well if you need quadmath support on ppc64le.

**Comment by sdebionne** [comment]
With https://github.com/boostorg/charconv/commit/100473b1dc3c3dfff0513e584c8f447824c7e34c we manage to build our Conda recipe for all platforms. Thank you!
