### ISSUE TITLE
Question: a way to hide #include <x86intrin.h> from public headers?

### ISSUE THREAD

**Issue by anarthal** [boostorg/charconv#201]
My build benchmark is flagging `boost/charconv/from_chars.hpp` (which I expected to be a lightweight header) as slow to include (taking ~1s). Looks like it's due to `#  include <x86intrin.h>`. Is it viable to avoid including this header in the public charconv headers?

**Comment by mborland** [comment]
Yes; looks like I stopped using the intrinsics a while ago, but never removed the headers.
