### ISSUE TITLE
from_chars integer impl mismatch in errc::invalid_argument with std::from_chars

### ISSUE THREAD

**Issue by deepak1556** [boostorg/charconv#213]
For the following example,

```c++
uint16_t segment_result{};
std::string_view input{"/c"};
auto r = std::from_chars(input.data(), input.data() + input.size(),
                        segment_result);
```

std::from_chars results in `std::errc::invalid_argument` while the boost implementation does not error - https://godbolt.org/z/WT7nPjeoK

**Comment by mborland** [comment]
This definetly is wrong from the boost side. Will take a look at this one too. Thanks again for clear bug reports.
