### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by gpeterhoff** [boostorg/charconv#89]
Hi Matt,
in quite a few files there are direct checks for msvc:
```#if BOOST_MSVC ...```
This generates warnings with other compilers. Please rewrite this to
```#if defined(BOOST_MSVC) && (BOOST_MSVC ...)```

thx
Gero

**Comment by mborland** [comment]
What toolchain and options gives you warnings? The CI runs cleanly with -Wextra and -Werror.

**Comment by pdimov** [comment]
-Wundef

**Comment by gpeterhoff** [comment]
-Wundef
In some other places there are warnings about -Wsign-conversion
